### ISSUE TITLE
UMD build not present in npm package

### ISSUE THREAD

**Issue by titus-anromedonn** [makerdao/dai.js#122]
The documentation states that you can use this as an UMD build, however, no UMD build is provided in the published npm repo.

In order to get the UMD build, you would have to clone the repo, and then manually build it, which defeats the purpose of using npm in the first place.

I was wondering if you guys could include that in the npm package for convenience purposes?

**Comment by levity** [comment]
Hmm, this is a good point. Sorry that the documentation is out of date.

These days it feels a little weird to me to include the UMD front-end build in the NPM module, since in the typical situation, it's being pulled into a project that has its own build toolchain. Is there a front-end package manager you like to use? I used to use Bower for this but I don't know whether it's the most popular or widely-used one these days.
