### ISSUE TITLE
CDP 60387 has different state when querying via @makerdao/dai versus graphql

### ISSUE THREAD

**Issue by savil** [makerdao/dai.js#170]
For CDP 60387, when i print info about it from the `@makerdao/dai` nodejs APIs, I get:

```
printing info for cdp.id 60387 :
debt: 0.06 DAI
gov fee: 0.00 MKR
collateralization ratio: 17.372915698915207
liquidation price: 14.95 USD/ETH USD per ETH
collateral value: 0.01 ETH
is safe: true
```

code for printing this is straightforward: https://gist.github.com/savil/1367a1b210df0de960a4115f5da1d870

but when i access it via graphiql https://sai-mainnet.makerfoundation.com/v1/console

```
{
  "data": {
    "getCup": {
      "lad": "0xBAf2258F1Ea98f460015abDf7F11dde10B74988c",
      "art": "0.935",
      "ratio": "111.4839510090815358389702105825624538000",
      "time": "2019-08-06T09:20:22+00:00",
      "ink": "0.005751994277790881",
      "deleted": false
    }
  }
}
```
This matches what i see on MKR tools: https://mkr.tools/cdp/60387

The art (debt) and ratio seem pretty different.

Any idea why this discrepancy?

**Comment by levity** [comment]
I don't know the root cause, but it appears that the GraphQL data is corrupt (and mkr.tools uses this same data). If you look at the history of actions on that CDP, it lists two transactions with four actions each, but [one of those transactions](http://ethtx.info/0xf51d779344a6562bdfe9c1147d4db82a5729e2281308b11a5faa32548b8397f9) actually corresponds to CDP 60390.

Thanks for bringing this to my attention; I'll see if we can figure out what's going on with the API.

**Comment by savil** [comment]
thanks @levity. Let me know if there's any further digging around i can help with from my end.

**Comment by savil** [comment]
@levity is there someone else you'd recommend pinging about the integrity of the graphql data?

**Comment by levity** [comment]
Sorry for the very delayed response. I recommend asking on the #dev channel of chat.makerdao.com. The GraphQL API for single-collateral Dai is reaching the end of its life now that SCD has been shut down though.
