### ISSUE TITLE
Creating a Maker instance on Ganache node

### ISSUE THREAD

**Issue by kawmaiparis** [makerdao/dai.js#212]
I got an error trying to create a Maker instance on my local Ganache node. I can't find an example online anywhere. What seems to be the problem here?

   const maker = await Maker.create("test", {
            privateKey: PRIVATE_KEY,
            url: "http://127.0.0.1:7545"
   });

Error: No network with ID 5777 found
    at getNetworkName (.....)
    ...

Thanks!

**Comment by b-pmcg** [comment]
When you start your local Ganache node, try setting the network ID to 999 using the `--networkId` flag. The error is occurring because 5777 is not currently supported in the SDK. You can see the supported network IDs here: https://github.com/makerdao/dai.js/blob/dev/packages/dai/contracts/networks.js#L146
